outputs:
  - template: CMakeLists.txt
    path: cpp/CMakeLists.txt
  - template: addon.cpp
    path: cpp/addon.cpp
    formatter: clang-format
  - template: class.h
    per: interface
    path: cpp/{{ snakeCase interface.name }}.h
    formatter: clang-format
  - template: class.cpp
    per: interface
    path: cpp/{{ snakeCase interface.name }}.cpp
    formatter: clang-format
  - template: dictionary.h
    per: dictionary
    path: cpp/{{ snakeCase dictionary.name }}.h
    formatter: clang-format
