outputs:
  - template: index
    path: ts/index.ts
    formatter: prettier --parser typescript
  - template: class
    per: interface
    path: ts/{{ interface.name }}.d.ts
    formatter: prettier --parser typescript
